// ── CATÁLOGO SWISS JUST ARGENTINA ────────────────────────────────────────
// Fuente: Lista de precios oficial + catálogo publicado

const CATALOG = [
  // ── AROMATERAPIA ──────────────────────────────────────────────────────
  { id:1,  emoji:"🌿", cat:"Aromaterapia", name:"Óleo 31 — 20ml",
    desc:"El ícono suizo: 31 aceites esenciales puros",
    tags:["dolor de cabeza","migraña","músculos","estrés","circulación","resfriado","versátil","oleo"] },
  { id:2,  emoji:"🌿", cat:"Aromaterapia", name:"Óleo 31 — 50ml",
    desc:"Formato familiar del clásico suizo",
    tags:["dolor de cabeza","migraña","músculos","estrés","familia","oleo"] },
  { id:3,  emoji:"🍋", cat:"Aromaterapia", name:"Aceite Esencial de Eucalipto",
    desc:"Vías respiratorias y energía mental",
    tags:["resfriado","congestión","respiración","sinusitis","gripe","eucalipto"] },
  { id:4,  emoji:"💜", cat:"Aromaterapia", name:"Aceite Esencial de Lavanda",
    desc:"Relajación, sueño profundo y calma",
    tags:["sueño","insomnio","estrés","ansiedad","relajación","lavanda"] },
  { id:5,  emoji:"🌱", cat:"Aromaterapia", name:"Aceite Esencial de Romero",
    desc:"Energía, concentración y circulación",
    tags:["energía","concentración","circulación","memoria","cabello","romero"] },
  { id:6,  emoji:"🟢", cat:"Aromaterapia", name:"Aceite Esencial de Menta",
    desc:"Frescor, claridad mental y digestión",
    tags:["digestión","náuseas","cabeza","frescor","concentración","menta"] },
  { id:7,  emoji:"🍊", cat:"Aromaterapia", name:"Aceite Esencial de Naranja",
    desc:"Alegría, energía y bienestar emocional",
    tags:["ánimo","alegría","energía","hogar","aromaterapia","naranja"] },
  { id:8,  emoji:"🌸", cat:"Aromaterapia", name:"Aceite Esencial de Manzanilla",
    desc:"Calma, piel sensible y digestión suave",
    tags:["piel sensible","calma","digestión","niños","manzanilla"] },
  { id:9,  emoji:"🌺", cat:"Aromaterapia", name:"Aceite Esencial de Geranio",
    desc:"Equilibrio hormonal y piel radiante",
    tags:["hormonas","piel","equilibrio","mujer","geranio"] },
  { id:10, emoji:"🍋", cat:"Aromaterapia", name:"Aceite Esencial de Bergamota",
    desc:"Uplifting natural para el estado de ánimo",
    tags:["ánimo","estrés","depresión","piel","bergamota"] },
  { id:11, emoji:"🍋", cat:"Aromaterapia", name:"Aceite Esencial de Limón",
    desc:"Purificante, energizante y antioxidante",
    tags:["energía","purificante","inmunidad","hogar","limón"] },
  { id:12, emoji:"🌿", cat:"Aromaterapia", name:"Aceite Esencial de Patchouli",
    desc:"Tierra, sensualidad y cuidado de la piel",
    tags:["piel","sensualidad","meditación","relajación","patchouli"] },
  { id:13, emoji:"💚", cat:"Aromaterapia", name:"Aceite Esencial de Tea Tree",
    desc:"Protección natural antibacteriana y antifúngica",
    tags:["antibacteriano","hongos","acné","piel","infecciones","tea tree"] },
  { id:14, emoji:"🌿", cat:"Aromaterapia", name:"Revitalizador Guduchi",
    desc:"Bienestar general, defensas y vitalidad",
    tags:["defensas","inmunidad","vitalidad","bienestar","energía","guduchi"] },
  { id:15, emoji:"✨", cat:"Aromaterapia", name:"Aceite Corporal Harmony+",
    desc:"Blend armonizante para cuerpo y mente",
    tags:["cuerpo","armonía","bienestar","masaje","harmony"] },

  // ── BIENESTAR EMOCIONAL ───────────────────────────────────────────────
  { id:16, emoji:"😌", cat:"Bienestar Emocional", name:"Anti-Stress Just",
    desc:"Fórmula suiza para calma y equilibrio emocional",
    tags:["estrés","ansiedad","nervios","relajación","tensión","anti-stress"] },
  { id:17, emoji:"🌬️", cat:"Bienestar Emocional", name:"Esencia para Baño de Melisa",
    desc:"Baño relajante antiestrés con melisa",
    tags:["baño","estrés","relajación","ansiedad","melisa","nervios"] },
  { id:18, emoji:"🌸", cat:"Bienestar Emocional", name:"Esencia para Baño de Sándalo",
    desc:"Relajación profunda y equilibrio emocional",
    tags:["baño","relajación","equilibrio","meditación","sándalo"] },
  { id:19, emoji:"🛁", cat:"Bienestar Emocional", name:"Espuma de Baño Hipérico & Bergamota",
    desc:"Baño revitalizante y antidepresivo natural",
    tags:["baño","ánimo","depresión","alegría","revitalizante","hipérico"] },

  // ── BIENESTAR FÍSICO ──────────────────────────────────────────────────
  { id:20, emoji:"🌬️", cat:"Bienestar Físico", name:"Eucasol Just",
    desc:"Spray de eucalipto para vías respiratorias",
    tags:["resfriado","tos","congestión","respiración","bronquitis","gripe","eucasol"] },
  { id:21, emoji:"🌱", cat:"Bienestar Físico", name:"Crema de Tomillo",
    desc:"Masajes en pecho y espalda — ideal en invierno",
    tags:["tos","bronquitis","gripe","pecho","invierno","respiración","tomillo"] },
  { id:22, emoji:"🛁", cat:"Bienestar Físico", name:"Esencia para Baño de Tomillo",
    desc:"Baño descongestionante y fortalecedor",
    tags:["baño","resfriado","bronquitis","invierno","tomillo","gripe"] },
  { id:23, emoji:"🌼", cat:"Bienestar Físico", name:"Gel Cremoso de Árnica",
    desc:"Alivia golpes, contusiones y dolor muscular",
    tags:["golpes","moratones","músculos","articulaciones","dolor","deporte","árnica"] },
  { id:24, emoji:"💚", cat:"Bienestar Físico", name:"Gel Cremoso de Consuelda",
    desc:"Reconfortante tras el esfuerzo físico",
    tags:["músculos","articulaciones","deporte","post-entrenamiento","flexibilidad","consuelda"] },
  { id:25, emoji:"🌲", cat:"Bienestar Físico", name:"Crema de Enebro",
    desc:"Calor muscular, flexibilidad y movimiento",
    tags:["músculos","articulaciones","calor","rigidez","masaje","enebro"] },
  { id:26, emoji:"🌿", cat:"Bienestar Físico", name:"Crema San'Activ — Sales del Mar Muerto",
    desc:"Minerales del Mar Muerto para piel y músculos",
    tags:["piel","músculos","minerales","mar muerto","terapéutico"] },
  { id:27, emoji:"🛁", cat:"Bienestar Físico", name:"Esencia para Baño de Enebro",
    desc:"Baño relajante muscular y articular",
    tags:["baño","músculos","relajación","articulaciones","enebro"] },
  { id:28, emoji:"✋", cat:"Bienestar Físico", name:"Bálsamo para el Cuerpo",
    desc:"Base preparatoria para todos los masajes",
    tags:["masaje","cuerpo","preparación","absorción","bálsamo"] },
  { id:29, emoji:"🌸", cat:"Bienestar Físico", name:"Espuma de Baño Flores de Heno & Edelweiss",
    desc:"Baño alpino purificante y reconfortante",
    tags:["baño","purificante","alpino","edelweiss","reconfortante"] },
  { id:30, emoji:"💨", cat:"Bienestar Físico", name:"Hand Gel con Naranja y Flores de Tilo",
    desc:"Gel higienizante natural con aromas florales",
    tags:["higiene","manos","antibacteriano","natural","naranja","tilo"] },

  // ── BIENESTAR DERMO-COSMÉTICO ─────────────────────────────────────────
  { id:31, emoji:"🏔️", cat:"Dermo-Cosmético", name:"Alpencreme",
    desc:"Crema nutritiva con hierbas de los Alpes suizos",
    tags:["piel","hidratación","nutrición","seca","alpina","crema"] },
  { id:32, emoji:"🌸", cat:"Dermo-Cosmético", name:"Crema de Manzanilla para Manos",
    desc:"Hidratación profunda para manos sensibles",
    tags:["manos","hidratación","sensible","suave","manzanilla"] },
  { id:33, emoji:"💜", cat:"Dermo-Cosmético", name:"Crema de Malva para el Rostro",
    desc:"Piel sensible e irritada — apta para niños",
    tags:["rostro","sensible","irritada","niños","bebé","malva"] },
  { id:34, emoji:"🫧", cat:"Dermo-Cosmético", name:"Crema de Tea Tree, Manuca y Rosalina",
    desc:"Cuidado profundo para piel con imperfecciones",
    tags:["acné","imperfecciones","piel grasa","antibacteriano","tea tree"] },
  { id:35, emoji:"🌸", cat:"Dermo-Cosmético", name:"Crema de Lavanda",
    desc:"Suavidad y calma para piel reactiva",
    tags:["piel reactiva","suave","calmante","lavanda","hidratación"] },
  { id:36, emoji:"🌼", cat:"Dermo-Cosmético", name:"Crema de Caléndula",
    desc:"Regeneración y protección de la piel",
    tags:["regeneración","cicatrices","protección","caléndula","piel"] },
  { id:37, emoji:"✨", cat:"Dermo-Cosmético", name:"Body Butter de Sándalo",
    desc:"Manteca corporal nutritiva y aromática",
    tags:["cuerpo","hidratación","nutritiva","aroma","sándalo","manteca"] },
  { id:38, emoji:"🧴", cat:"Dermo-Cosmético", name:"Loción Cremosa de Malva",
    desc:"Hidratación corporal para pieles sensibles",
    tags:["cuerpo","hidratación","malva","sensible","loción"] },
  { id:39, emoji:"💆", cat:"Dermo-Cosmético", name:"Loción Cremosa de Almendras",
    desc:"Nutrición profunda y suavidad para el cuerpo",
    tags:["cuerpo","nutrición","suavidad","almendras","loción"] },
  { id:40, emoji:"🌊", cat:"Dermo-Cosmético", name:"Espuma de Baño Algas Marinas & Té Verde",
    desc:"Detox marino para piel luminosa y firme",
    tags:["detox","algas","antioxidante","luminosidad","baño","té verde"] },

  // ── PIES Y PIERNAS ────────────────────────────────────────────────────
  { id:41, emoji:"🦵", cat:"Pies y Piernas", name:"Pedibalm — Loción para Piernas",
    desc:"Piernas cansadas, pesadas y con mala circulación",
    tags:["piernas","circulación","cansancio","pesadas","varices","pedibalm"] },
  { id:42, emoji:"🦶", cat:"Pies y Piernas", name:"Pedicream — Crema para los Pies",
    desc:"Hidratación y suavidad para pies agrietados",
    tags:["pies","talones","grietas","hidratación","suavidad","pedicream"] },
  { id:43, emoji:"💨", cat:"Pies y Piernas", name:"Pedibon Spray — Desodorante para Pies",
    desc:"Frescura y protección natural para los pies",
    tags:["pies","desodorante","frescura","olor","spray","pedibon"] },
  { id:44, emoji:"🌊", cat:"Pies y Piernas", name:"Pedibath — Baño para Pies",
    desc:"Relax y cuidado completo para tus pies",
    tags:["pies","baño","relajación","cuidado","pedibath"] },
  { id:45, emoji:"🫧", cat:"Pies y Piernas", name:"Pediscrub — Exfoliante para Pies",
    desc:"Elimina durezas y suaviza la planta del pie",
    tags:["pies","exfoliante","durezas","suavidad","pediscrub"] },
  { id:46, emoji:"💚", cat:"Pies y Piernas", name:"Venen Gel — Gel para Piernas",
    desc:"Gel refrescante para piernas con varices o cansancio",
    tags:["varices","piernas","circulación","frescor","gel","venen"] },

  // ── CUIDADO CAPILAR ───────────────────────────────────────────────────
  { id:47, emoji:"💆", cat:"Cuidado Capilar", name:"Shampoo de Tea Tree, Manuca y Rosalina",
    desc:"Cuero cabelludo con caspa o irritación",
    tags:["caspa","cuero cabelludo","irritación","shampoo","tea tree"] },
  { id:48, emoji:"🌿", cat:"Cuidado Capilar", name:"Shampoo San'Activ",
    desc:"Cabello graso con volumen y frescura",
    tags:["cabello graso","volumen","frescura","shampoo","san activ"] },
  { id:49, emoji:"🌱", cat:"Cuidado Capilar", name:"Shampoo Capilar con Nim",
    desc:"Anti-caída y fortalecimiento del cabello",
    tags:["caída","cabello débil","fortalecimiento","nim","shampoo"] },
  { id:50, emoji:"✨", cat:"Cuidado Capilar", name:"Máscara Capilar con Arándanos",
    desc:"Hidratación profunda y brillo para el cabello",
    tags:["cabello seco","brillo","hidratación","mascarilla","arándanos"] },

  // ── VITAL JUST (FACIAL ANTIEDAD) ──────────────────────────────────────
  { id:51, emoji:"⭐", cat:"Vital Just", name:"Vital Just — Gel Limpiador",
    desc:"Limpieza facial suave y eficaz",
    tags:["limpieza","facial","poros","diaria","vital just"] },
  { id:52, emoji:"⭐", cat:"Vital Just", name:"Vital Just — Crema Hidratante de Día FPS15",
    desc:"Hidratación diaria con protección solar",
    tags:["hidratación","día","FPS","facial","antiedad","vital just"] },
  { id:53, emoji:"⭐", cat:"Vital Just", name:"Vital Just — Crema de Noche Redensificante",
    desc:"Regeneración nocturna y firmeza de la piel",
    tags:["noche","antiedad","firmeza","regeneración","facial","vital just"] },
  { id:54, emoji:"⭐", cat:"Vital Just", name:"Vital Just — Sérum Reparador",
    desc:"Tratamiento intensivo antiedad de alta eficacia",
    tags:["antiedad","arrugas","sérum","intensivo","facial","vital just"] },
  { id:55, emoji:"⭐", cat:"Vital Just", name:"Vital Just — Mascarilla Renovación Intensiva",
    desc:"Renovación celular para piel luminosa",
    tags:["mascarilla","luminosidad","renovación","antiedad","vital just"] },
  { id:56, emoji:"⭐", cat:"Vital Just", name:"Vital Just — Crema Contorno de Ojos y Labios",
    desc:"Trata las zonas más delicadas del rostro",
    tags:["ojos","labios","contorno","antiedad","delicada","vital just"] },

  // ── CELLFIT (ANTICELULITIS) ────────────────────────────────────────────
  { id:57, emoji:"💪", cat:"Cellfit", name:"Gel Anti-Celulitis de Día Cellfit",
    desc:"Tratamiento reductor y reafirmante de día",
    tags:["celulitis","reafirmante","reductor","día","cellfit"] },
  { id:58, emoji:"💪", cat:"Cellfit", name:"Crema Anti-Celulitis de Noche Cellfit",
    desc:"Acción drenante y remodeladora nocturna",
    tags:["celulitis","noche","drenante","remodeladora","cellfit"] },
  { id:59, emoji:"💪", cat:"Cellfit", name:"Crema Exfoliante Corporal Cellfit",
    desc:"Exfolia y activa la circulación para reducir celulitis",
    tags:["celulitis","exfoliante","circulación","cuerpo","cellfit"] },
  { id:60, emoji:"💪", cat:"Cellfit", name:"Crema Reafirmante para el Busto Cellfit",
    desc:"Firmeza y tonicidad para el escote y busto",
    tags:["busto","firmeza","escote","tonicidad","cellfit"] },
];

// ── PREGUNTAS FRECUENTES / QUICK TOPICS ──────────────────────────────────
const QUICK_TOPICS = {
  stress:     [16, 17, 1, 4],
  dolor:      [23, 24, 25, 1],
  resfriado:  [20, 21, 3, 22],
  sueño:      [4, 17, 18, 16],
  energia:    [14, 5, 16, 15],
  piel:       [33, 31, 36, 37],
  cabello:    [47, 49, 50, 48],
  piernas:    [41, 46, 44, 42],
  antiedad:   [53, 52, 54, 56],
  celulitis:  [57, 58, 59, 60],
  aromaterapia:[1, 16, 4, 14],
  bano:       [17, 27, 18, 29],
};
